<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="task" nsURI="http://www.eclipselabs.org/etrack/domain/task"
    nsPrefix="org.eclipselabs.etrack.domain.task">
  <eClassifiers xsi:type="ecore:EClass" name="Attachment" eSuperTypes="#//Artifact ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//AssignableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeInBytes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataContainer" eType="#//AttachmentData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachmentData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdOn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//AssignableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdOn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Duration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="units" eType="#//DurationUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DurationUnit">
    <eLiterals name="MINUTES" literal="m"/>
    <eLiterals name="HOURS" value="1" literal="h"/>
    <eLiterals name="DAYS" value="2" literal="d"/>
    <eLiterals name="WEEKS" value="3" literal="w"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="../../org.eclipselabs.etrack.domain.data/model/data.ecore#//Linkable ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//AssignableItem ../../org.eclipselabs.etrack.domain.audit/model/audit.ecore#//AuditableItem ../../org.eclipselabs.etrack.domain.data/model/data.ecore#//CategorizedItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdOn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdBy" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1"
        eType="#//Attachment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribers" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TaskType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass ../../org.eclipselabs.etrack.domain.project/model/project.ecore#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTasks" upperBound="-1"
        eType="#//RelatedTasksMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolution" eType="#//TaskResolution"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolvedOn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedBy" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dueOn" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startedOn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estimate" eType="#//Duration"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correctedEstimate" eType="#//Duration"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//TaskGroup"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDomain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//StateTransition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateGroups" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//StateGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//TaskRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolutions" upperBound="-1"
        eType="#//TaskResolution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskTypes" upperBound="-1"
        eType="#//TaskType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//StateTransitionMapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//TaskRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedStates" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.state/model/state.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolutions" upperBound="-1"
        eType="#//TaskResolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingResolution" lowerBound="1"
        eType="#//TaskResolution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskModelVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskAttributeChange" eSuperTypes="../../org.eclipselabs.etrack.domain.audit/model/audit.ecore#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDomainLink" eSuperTypes="../../org.eclipselabs.etrack.domain.data/model/data.ecore#//LinkedContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDomain" lowerBound="1"
        eType="#//TaskDomain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelatedTasksMapping" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//TaskRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//TaskRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskResolution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.project/model/project.ecore#//Project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskQuery" eSuperTypes="../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//AssignableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
