<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project" nsURI="http://www.eclipselabs.org/etrack/domain/project"
    nsPrefix="org.eclipselabs.etrack.domain.project">
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="../../org.eclipselabs.etrack.domain.data/model/data.ecore#//Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="-1"
        eType="#//Team" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admins" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Identity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="../../org.eclipselabs.etrack.domain.security/model/security.ecore#//PermissionGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTeams" upperBound="-1"
        eType="#//Team" containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
