<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="database"
    nsURI="http://www.eclipselabs.org/etrack/domain/database" nsPrefix="org.eclipselabs.etrack.domain.database">
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDomain" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.task/model/task.ecore#//TaskDomain"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.task/model/task.ecore#//Task"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Entity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accountRequests" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.account/model/account.ecore#//AccountRequest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.account/model/account.ecore#//Account"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
