<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="state" nsURI="http://www.eclipselabs.org/etrack/domain/state"
    nsPrefix="org.eclipselabs.etrack.domain.state">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransitionMapping" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//StateTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateChange" eSuperTypes="../../org.eclipselabs.etrack.domain.audit/model/audit.ecore#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="#//StateTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//StateTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionsByState" upperBound="-1"
        eType="#//StateTransitionMapping" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
